### ISSUE TITLE
Can anyone make it Responsive for mobile devices?

### ISSUE THREAD

**Issue by Yash-srivastav16** [Yash-srivastav16/Tour-Project#5]

**Comment by Igaurav31** [comment]
I saw your github pages deplyment, seems like the site is already responsive. Can you please describe your issue?

**Comment by Yash-srivastav16** [comment]
Please check when using mobile device the things are scattered and fonts are large. 
Check screenshot from mobile device
![Screenshot_2023-07-02-08-50-52-883_com.android.chrome.jpg](https://github.com/Yash-srivastav16/Tour-Project/assets/100063377/bd499444-4633-4215-9f4d-a3e2cf61d65e)

**Comment by summerkoushal** [comment]
i want to work on this issue.

**Comment by Yash-srivastav16** [comment]
Ok @summerkoushal assigned you the issue.

**Comment by summerkoushal** [comment]
thanks for assigning, will be in touch with you frequently.

**Comment by summerkoushal** [comment]
hey, i created a pull request.
Do merge it, if you like. Also if by any chance any changes are required, then feel free to pin me out !!

**Comment by Yash-srivastav16** [comment]
Looks Good, Thanks Bro for the changes.

**Comment by summerkoushal** [comment]
your welcome mate !
